# Generated by Django 5.1.3 on 2024-12-14 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0002_initial'),
    ]

    operations = [
    ]
