# Generated by Django 5.1.3 on 2024-12-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0003_auto_20241214_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
