# Generated by Django 5.1.3 on 2024-12-16 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0005_homestay_approved_room_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.AddField(
            model_name='booking',
            name='homestay',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homestay.homestay'),
            preserve_default=False,
        ),
    ]
