# Generated by Django 5.1.3 on 2024-12-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0006_remove_booking_status_booking_homestay'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Cancelled', 'Cancelled')], default='Booked', max_length=20),
        ),
    ]
