# Generated by Django 5.1.3 on 2024-12-17 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0009_alter_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
